.catalog:
  name: Jenkins
  version: 2.32.2-rancher
  description: |
    Jenkins CI management server.
  questions:
  - variable: "PORT"
    type: "int"
    label: "Port Number"
    description: "Which port should Jenkins listen on?"
    default: 8080
    required: true
  - variable: "volume_work"
    description: "Work volume to save jenkins data"
    label: "Work volume:"
    required: true
    default: "/var/lib/docker/jenkins-ci"
    type: "string"
